import 'product_model.dart';

const List<String> productCategories = [
  'Semua',
  'Elektronik',
  'Fashion Pria',
  'Fashion Wanita',
  'Makanan',
  'Olahraga',
  'Kecantikan',
  'Rumah Tangga',
];

const List<Product> dummyProducts = [
  // Elektronik
  Product(
    id: '1',
    name: 'Headphone Bluetooth JBL Tune 520BT Premium Wireless Bass',
    imageUrl: 'https://picsum.photos/seed/headphone/300/300',
    price: 499000,
    originalPrice: 799000,
    discountPercent: 38,
    rating: 4.8,
    sold: 12500,
    location: 'Jakarta',
    category: 'Elektronik',
    isFreeShipping: true,
    isOfficial: true,
  ),
  Product(
    id: '2',
    name: 'Smartwatch Samsung Galaxy Watch 6 Classic AMOLED',
    imageUrl: 'https://picsum.photos/seed/smartwatch/300/300',
    price: 3299000,
    originalPrice: 4299000,
    discountPercent: 23,
    rating: 4.9,
    sold: 8200,
    location: 'Surabaya',
    category: 'Elektronik',
    isFreeShipping: true,
    isOfficial: true,
  ),
  Product(
    id: '3',
    name: 'Charger GaN 65W USB-C Fast Charging Multi Port',
    imageUrl: 'https://picsum.photos/seed/charger/300/300',
    price: 189000,
    originalPrice: 250000,
    discountPercent: 24,
    rating: 4.7,
    sold: 35000,
    location: 'Bandung',
    category: 'Elektronik',
    isFreeShipping: false,
  ),
  Product(
    id: '4',
    name: 'Laptop Gaming ASUS ROG Strix G15 RTX 4060 16GB RAM',
    imageUrl: 'https://picsum.photos/seed/laptop/300/300',
    price: 16999000,
    originalPrice: 19999000,
    discountPercent: 15,
    rating: 4.6,
    sold: 1200,
    location: 'Jakarta',
    category: 'Elektronik',
    isFreeShipping: true,
    isOfficial: true,
  ),

  // Fashion Pria
  Product(
    id: '5',
    name: 'Kaos Polos Pria Cotton Combed 30s Premium Unisex',
    imageUrl: 'https://picsum.photos/seed/kaos/300/300',
    price: 75000,
    originalPrice: 120000,
    discountPercent: 37,
    rating: 4.8,
    sold: 56000,
    location: 'Bandung',
    category: 'Fashion Pria',
    isFreeShipping: true,
  ),
  Product(
    id: '6',
    name: 'Celana Jogger Pria Distro Keren Slim Fit Casual',
    imageUrl: 'https://picsum.photos/seed/jogger/300/300',
    price: 130000,
    originalPrice: 180000,
    discountPercent: 28,
    rating: 4.7,
    sold: 22000,
    location: 'Yogyakarta',
    category: 'Fashion Pria',
    isFreeShipping: false,
  ),
  Product(
    id: '7',
    name: 'Sepatu Sneakers Pria Nike Air Force Premium Quality',
    imageUrl: 'https://picsum.photos/seed/sneakers/300/300',
    price: 350000,
    originalPrice: 500000,
    discountPercent: 30,
    rating: 4.5,
    sold: 9800,
    location: 'Jakarta',
    category: 'Fashion Pria',
    isFreeShipping: true,
  ),

  // Fashion Wanita
  Product(
    id: '8',
    name: 'Dress Wanita Korean Style Midi Floral Summer Casual',
    imageUrl: 'https://picsum.photos/seed/dress/300/300',
    price: 185000,
    originalPrice: 280000,
    discountPercent: 34,
    rating: 4.8,
    sold: 18900,
    location: 'Surabaya',
    category: 'Fashion Wanita',
    isFreeShipping: true,
  ),
  Product(
    id: '9',
    name: 'Tas Wanita Shoulder Bag Import Branded Look Tote Bag',
    imageUrl: 'https://picsum.photos/seed/tote/300/300',
    price: 225000,
    originalPrice: 350000,
    discountPercent: 36,
    rating: 4.6,
    sold: 14500,
    location: 'Jakarta',
    category: 'Fashion Wanita',
    isFreeShipping: false,
  ),
  Product(
    id: '10',
    name: 'Sepatu Heels Wanita Block Heel Formal Cantik Elegant',
    imageUrl: 'https://picsum.photos/seed/heels/300/300',
    price: 170000,
    originalPrice: 250000,
    discountPercent: 32,
    rating: 4.5,
    sold: 8700,
    location: 'Semarang',
    category: 'Fashion Wanita',
    isFreeShipping: true,
  ),

  // Makanan
  Product(
    id: '11',
    name: 'Coklat Silverqueen 95gr Assorted Rasa Mix Cokelat Susu',
    imageUrl: 'https://picsum.photos/seed/coklat/300/300',
    price: 22000,
    rating: 4.9,
    sold: 120000,
    location: 'Jakarta',
    category: 'Makanan',
    isFreeShipping: false,
  ),
  Product(
    id: '12',
    name: 'Kopi Arabika Gayo Premium Single Origin Aceh 250gr',
    imageUrl: 'https://picsum.photos/seed/kopi/300/300',
    price: 89000,
    originalPrice: 120000,
    discountPercent: 26,
    rating: 4.9,
    sold: 32000,
    location: 'Aceh',
    category: 'Makanan',
    isFreeShipping: true,
    isOfficial: true,
  ),
  Product(
    id: '13',
    name: 'Snack Keripik Singkong Balado Pedas Manis 500gr',
    imageUrl: 'https://picsum.photos/seed/keripik/300/300',
    price: 35000,
    rating: 4.7,
    sold: 45000,
    location: 'Bandung',
    category: 'Makanan',
    isFreeShipping: false,
  ),

  // Olahraga
  Product(
    id: '14',
    name: 'Dumbbell Barbel Set 20kg Rubber Anti Slip Gym Fitness',
    imageUrl: 'https://picsum.photos/seed/dumbbell/300/300',
    price: 280000,
    originalPrice: 400000,
    discountPercent: 30,
    rating: 4.6,
    sold: 7800,
    location: 'Bekasi',
    category: 'Olahraga',
    isFreeShipping: true,
  ),
  Product(
    id: '15',
    name: 'Sepeda Lipat Pacific Noris 20 Inch 6 Speed Alloy',
    imageUrl: 'https://picsum.photos/seed/sepeda/300/300',
    price: 1899000,
    originalPrice: 2500000,
    discountPercent: 24,
    rating: 4.7,
    sold: 3200,
    location: 'Jakarta',
    category: 'Olahraga',
    isFreeShipping: true,
    isOfficial: true,
  ),

  // Kecantikan
  Product(
    id: '16',
    name: 'Serum Vitamin C 20% Brightening Anti Aging Ms Glow',
    imageUrl: 'https://picsum.photos/seed/serum/300/300',
    price: 99000,
    originalPrice: 150000,
    discountPercent: 34,
    rating: 4.8,
    sold: 89000,
    location: 'Jakarta',
    category: 'Kecantikan',
    isFreeShipping: true,
    isOfficial: true,
  ),
  Product(
    id: '17',
    name: 'Sunscreen SPF50 PA++++ Anessa Whitening Milk UV Lotion',
    imageUrl: 'https://picsum.photos/seed/sunscreen/300/300',
    price: 199000,
    originalPrice: 280000,
    discountPercent: 29,
    rating: 4.9,
    sold: 45000,
    location: 'Surabaya',
    category: 'Kecantikan',
    isFreeShipping: true,
  ),

  // Rumah Tangga
  Product(
    id: '18',
    name: 'Rice Cooker Cosmos 2 Liter Multi Function Premium',
    imageUrl: 'https://picsum.photos/seed/ricecooker/300/300',
    price: 320000,
    originalPrice: 450000,
    discountPercent: 29,
    rating: 4.7,
    sold: 21000,
    location: 'Jakarta',
    category: 'Rumah Tangga',
    isFreeShipping: true,
    isOfficial: true,
  ),
  Product(
    id: '19',
    name: 'Panci Set Anti Lengket Granite Marble 5 in 1 Cookware',
    imageUrl: 'https://picsum.photos/seed/panci/300/300',
    price: 289000,
    originalPrice: 450000,
    discountPercent: 36,
    rating: 4.6,
    sold: 9500,
    location: 'Semarang',
    category: 'Rumah Tangga',
    isFreeShipping: false,
  ),
  Product(
    id: '20',
    name: 'Vacuum Cleaner Robot Xiaomi Mi Robot S10 Wet & Dry',
    imageUrl: 'https://picsum.photos/seed/vacuum/300/300',
    price: 2199000,
    originalPrice: 3200000,
    discountPercent: 31,
    rating: 4.8,
    sold: 4100,
    location: 'Jakarta',
    category: 'Rumah Tangga',
    isFreeShipping: true,
    isOfficial: true,
  ),
];
